name: Merge Main into Feature Branches

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      # Step 2: Set up Git user info
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 3: Fetch all branches
      - name: Fetch all branches
        run: git fetch --all

      # Step 4: Iterate through all branches and merge main into each
      # - name: Merge main into all feature branches
      #   run: |
      #     # Get a list of all branches (excluding main)
      #     for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'); do
      #       echo "Merging main into $branch"
      #       git checkout $branch
      #       git merge origin/main --no-ff --no-edit || echo "Conflict in $branch, manual resolution needed"
      #       git push origin $branch || echo "Failed to push $branch"
      #     done


      - name: Show feature branches
        run: |
          echo "Feature branches:"
          git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'

      # Step 4: Iterate through all branches and merge main into each
      - name: Merge main into all feature branches
        run: |
          # Get a list of all branches (excluding main)
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'); do
            echo "Merging main into $branch"
            git checkout $branch
            
            echo "branch name: $branch"

            # Pull the latest changes for the branch to ensure it's up to date
            git pull origin $branch
            
            # Merge the changes from main
            git merge origin/main --no-ff --no-edit
            
            # Check if the merge was successful before pushing
            if [ $? -eq 0 ]; then
              git push origin $branch || echo "Failed to push $branch"
            else
              echo "Conflict in $branch, manual resolution needed"
            fi
          done