name: Merge Main into Feature Branches

on:
  push:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch all branches
        run: git fetch --all

      # Step 4: Iterate through all branches and merge main into each
      # - name: Merge main into all feature branches
      #   run: |
      #     # Get a list of all branches (excluding main)
      #     for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'); do
      #       echo "Merging main into $branch"
      #       git checkout $branch
      #       git merge origin/main --no-ff --no-edit || echo "Conflict in $branch, manual resolution needed"
      #       git push origin $branch || echo "Failed to push $branch"
      #     done

      - name: Show all branches
        run: |
          echo "All branches:"
          git branch -a  # List all local and remote branches

      #this would be remove after testing    
      - name: Show feature branches
        run: |
          echo "Feature branches:"
          branches=$(git branch -r | grep -v 'origin/main' || true)
          if [ -z "$branches" ]; then
            echo "No feature branches found."
          else
            echo "$branches"
          fi

      - name: Configure Git Authentication
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_PAT }}@github.com/svensson1982/core-web.git
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}

      - name: Merge tokens directory from main into all feature branches
        run: |
          # Iterate through remote feature branches
          for branch in $(git branch -r | grep -v 'origin/main'); do
            branch_name=$(echo $branch | sed 's|origin/||')  # Remove 'origin/' prefix
            echo "Merging tokens directory from main into $branch_name"
            
            # Check out the remote branch
            git checkout -b $branch_name origin/$branch_name
            
            # Pull the latest changes for the branch to ensure it's up to date
            git pull origin $branch_name
            
            # Copy only the tokens directory from main to the current branch
            git checkout origin/main -- tokens/
            
            # Check if there are any changes to commit
            if [[ $(git status --porcelain) ]]; then
              echo "Changes detected in tokens directory."
              git add tokens/
              git commit -m "Merged tokens directory from main into $branch_name"
              
              # Push changes using PAT for authentication
              git push https://x-access-token:${{ secrets.GIT_PAT  }}@github.com/svensson1982/core-web.git $branch_name || echo "Failed to push $branch_name"
            else
              echo "No changes in tokens directory for $branch_name."
            fi
          done

        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        #this is the end  